name: CI

on: [pull_request, push]

permissions:
  attestations: write
  id-token: write
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables and Save to File
        run: |
          echo "QBT_VERSION=v5.0.1" > versions.txt
          echo "QBT_LOCAL_VERSION=v4.9.9" >> versions.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: versions_file
          path: versions.txt

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: versions_file
          path: .
      - name: Read and Set Environment Variables
        run: |
          source versions.txt
          echo "QBT_VERSION is $QBT_VERSION"
          echo "QBT_LOCAL_VERSION is $QBT_LOCAL_VERSION"

