name: CI

on: [pull_request, push]

permissions:
  attestations: write
  id-token: write
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  job_one:
    runs-on: ubuntu-latest
    outputs:
      version_file: ${{ steps.set_output.outputs.file_path }}
    steps:
      - name: Set Environment Variable
        run: |
          echo "QBT_VERSION=v5.0.1" > version.txt
          echo "QBT_LOCAL_VERSION=v5.0.2" > version.txt
        id: set_output
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: version_file
          path: version.txt

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: version_file
          path: .
      - name: Read and Set Environment Variable
        run: |
          source version.txt
          echo "QBT_VERSION is $QBT_VERSION"
          echo "QBT_LOCAL_VERSION is $QBT_LOCAL_VERSION"

