name: CI

on: [pull_request, push]

permissions:
  attestations: write
  id-token: write
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  job_one:
    runs-on: ubuntu-latest
    outputs:
      QBT_VERSION: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Set QBT_VERSION Output
        id: set_version
        run: |
          echo "v5.0.1"  # Replace with logic to set the version dynamically
          echo "::set-output name=version::v5.0.1"

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Use QBT_VERSION Output from Job One
        run: |
          echo "QBT_VERSION from job_one is ${{ needs.job_one.outputs.QBT_VERSION }}"
